---
title: "samplingbook"
author: "Kurt Schulzke"
format: html
editor: visual
---

# Library
```{r}
library(samplingbook)
```

# Sprop

```{r}
Sprop(m=45, n=100, N=300)
Sprop(m=2, n=100, N=300)
```
# pps sampling

See https://rdrr.io/cran/samplingbook/man/pps.sampling.html. 
```{r}
## 1) simple suppositious example
data <- data.frame(id = 1:7, z = c(1.8, 2 ,3.2 ,2.9 ,1.5 ,2.0 ,2.2))

# Usage of pps.sampling for Sampford method
set.seed(178209)
pps.sample_sampford <- pps.sampling(z=data$z, n=2, method='sampford', return.PI=FALSE)
pps.sample_sampford

# sampling elements
id.sample <- pps.sample_sampford$sample
id.sample

# other methods
set.seed(178209)
pps.sample_tille <- pps.sampling(z=data$z, n=2, method='tille')
pps.sample_tille

set.seed(178209)
pps.sample_midzuno <- pps.sampling(z=data$z, n=2, method='midzuno')
pps.sample_midzuno

set.seed(178209)
pps.sample_madow <- pps.sampling(z=data$z, n=2, method='madow')
pps.sample_madow
```

# midzuno
## data
```{r}
## 2) influenza
data(influenza)
summary(influenza)
```

## run sample
```{r}
set.seed(108506)
pps <- pps.sampling(z=influenza$population,n=20,method='midzuno')
pps
sample <- influenza[pps$sample,]
sample
```

# Bootcamp_52

## Libraries
```{r}
library(readxl)
```

## Data
```{r}
Bootcamp_52 <- read_excel("Bootcamp_52.xlsx")

```

## pps sample

```{r}
set.seed(25)
BC.pps <- pps.sampling(z=Bootcamp_52$Sales,n=10,method='midzuno')
BC.pps
BC.sample <- Bootcamp_52[BC.pps$sample,]
BC.sample
```

